/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness / readiness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List domains
         * @description Allowed sort fields: `title` (default).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                    /** @description Case-insensitive match on title. LIKE wildcards (`%`, `_`) are treated as literals. Match mode controlled by `search_type`. */
                    search?: components["parameters"]["searchParam"];
                    /** @description How to match the search term against title. Only applies when `search` is non-empty. */
                    search_type?: components["parameters"]["searchTypeParam"];
                    /** @description Field to sort by (entity-specific; see endpoint description for allowed values). Defaults to `title`. */
                    sort?: components["parameters"]["sortParam"];
                    /** @description Sort direction. */
                    order?: components["parameters"]["orderParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Domain"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination or search params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized (when bearer required) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /** Create domain */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TitleBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Domain"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
            };
            cookie?: never;
        };
        /** Get domain */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Domain"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete domain
         * @description Fails with **400** if the domain still has users, groups, resources, access types, permissions, or related rows (foreign key RESTRICT).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request (e.g. entity still referenced) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Patch domain (title) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchTitleBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Domain"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/domains/{domainID}/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
            };
            cookie?: never;
        };
        /**
         * List users in domain
         * @description Allowed sort fields: `title` (default).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                    /** @description Case-insensitive match on title. LIKE wildcards (`%`, `_`) are treated as literals. Match mode controlled by `search_type`. */
                    search?: components["parameters"]["searchParam"];
                    /** @description How to match the search term against title. Only applies when `search` is non-empty. */
                    search_type?: components["parameters"]["searchTypeParam"];
                    /** @description Field to sort by (entity-specific; see endpoint description for allowed values). Defaults to `title`. */
                    sort?: components["parameters"]["sortParam"];
                    /** @description Sort direction. */
                    order?: components["parameters"]["orderParam"];
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["User"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination or search params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /** Create user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TitleBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/users/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                userID: components["parameters"]["userID"];
            };
            cookie?: never;
        };
        /** Get user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    userID: components["parameters"]["userID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete user
         * @description Fails with **400** if the user still has group memberships or direct permission grants.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    userID: components["parameters"]["userID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Patch user (title) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    userID: components["parameters"]["userID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchTitleBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/domains/{domainID}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
            };
            cookie?: never;
        };
        /**
         * List groups
         * @description Allowed sort fields: `title` (default).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                    /** @description Case-insensitive match on title. LIKE wildcards (`%`, `_`) are treated as literals. Match mode controlled by `search_type`. */
                    search?: components["parameters"]["searchParam"];
                    /** @description How to match the search term against title. Only applies when `search` is non-empty. */
                    search_type?: components["parameters"]["searchTypeParam"];
                    /** @description Field to sort by (entity-specific; see endpoint description for allowed values). Defaults to `title`. */
                    sort?: components["parameters"]["sortParam"];
                    /** @description Sort direction. */
                    order?: components["parameters"]["orderParam"];
                    /** @description Filter groups by parent group ID. */
                    parent_group_id?: string;
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Group"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination or search params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /** Create group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GroupCreateBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Group"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/groups/{groupID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                groupID: components["parameters"]["groupID"];
            };
            cookie?: never;
        };
        /** Get group */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    groupID: components["parameters"]["groupID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Group"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete group
         * @description Fails with **400** if the group has members, child groups, or group permission grants.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    groupID: components["parameters"]["groupID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Patch group (title and/or parent) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    groupID: components["parameters"]["groupID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GroupPatchBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Group"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/domains/{domainID}/groups/{groupID}/parent": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                groupID: components["parameters"]["groupID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set group parent */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    groupID: components["parameters"]["groupID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ParentBody"];
                };
            };
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/domains/{domainID}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
            };
            cookie?: never;
        };
        /**
         * List resources
         * @description Allowed sort fields: `title` (default).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                    /** @description Case-insensitive match on title. LIKE wildcards (`%`, `_`) are treated as literals. Match mode controlled by `search_type`. */
                    search?: components["parameters"]["searchParam"];
                    /** @description How to match the search term against title. Only applies when `search` is non-empty. */
                    search_type?: components["parameters"]["searchTypeParam"];
                    /** @description Field to sort by (entity-specific; see endpoint description for allowed values). Defaults to `title`. */
                    sort?: components["parameters"]["sortParam"];
                    /** @description Sort direction. */
                    order?: components["parameters"]["orderParam"];
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Resource"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination or search params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /** Create resource */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TitleBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/resources/{resourceID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                resourceID: components["parameters"]["resourceID"];
            };
            cookie?: never;
        };
        /** Get resource */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    resourceID: components["parameters"]["resourceID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete resource
         * @description Fails with **400** while permissions still reference this resource.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    resourceID: components["parameters"]["resourceID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Patch resource (title) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    resourceID: components["parameters"]["resourceID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchTitleBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/domains/{domainID}/access-types": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
            };
            cookie?: never;
        };
        /**
         * List access types
         * @description Allowed sort fields: `title` (default).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                    /** @description Case-insensitive match on title. LIKE wildcards (`%`, `_`) are treated as literals. Match mode controlled by `search_type`. */
                    search?: components["parameters"]["searchParam"];
                    /** @description How to match the search term against title. Only applies when `search` is non-empty. */
                    search_type?: components["parameters"]["searchTypeParam"];
                    /** @description Field to sort by (entity-specific; see endpoint description for allowed values). Defaults to `title`. */
                    sort?: components["parameters"]["sortParam"];
                    /** @description Sort direction. */
                    order?: components["parameters"]["orderParam"];
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AccessType"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination or search params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /** Create access type */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccessTypeCreateBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessType"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/access-types/{accessTypeID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                accessTypeID: components["parameters"]["accessTypeID"];
            };
            cookie?: never;
        };
        /** Get access type */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    accessTypeID: components["parameters"]["accessTypeID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessType"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete access type */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    accessTypeID: components["parameters"]["accessTypeID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Patch access type */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    accessTypeID: components["parameters"]["accessTypeID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccessTypePatchBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessType"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict (e.g. duplicate bit in domain) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/domains/{domainID}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
            };
            cookie?: never;
        };
        /**
         * List permissions
         * @description Allowed sort fields: `title` (default), `resource_id`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                    /** @description Case-insensitive match on title. LIKE wildcards (`%`, `_`) are treated as literals. Match mode controlled by `search_type`. */
                    search?: components["parameters"]["searchParam"];
                    /** @description How to match the search term against title. Only applies when `search` is non-empty. */
                    search_type?: components["parameters"]["searchTypeParam"];
                    /** @description Field to sort by (entity-specific; see endpoint description for allowed values). Defaults to `title`. */
                    sort?: components["parameters"]["sortParam"];
                    /** @description Sort direction. */
                    order?: components["parameters"]["orderParam"];
                    /** @description Filter permissions by resource ID. */
                    resource_id?: string;
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Permission"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination or search params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        /** Create permission */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PermissionCreateBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Permission"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/permissions/{permissionID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                permissionID: components["parameters"]["permissionID"];
            };
            cookie?: never;
        };
        /** Get permission */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    permissionID: components["parameters"]["permissionID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Permission"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete permission
         * @description Fails with **400** while user or group grants still reference this permission.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    permissionID: components["parameters"]["permissionID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Patch permission */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    permissionID: components["parameters"]["permissionID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PermissionPatchBody"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Permission"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/domains/{domainID}/users/{userID}/groups/{groupID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                userID: components["parameters"]["userID"];
                groupID: components["parameters"]["groupID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add user to group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    userID: components["parameters"]["userID"];
                    groupID: components["parameters"]["groupID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        /** Remove user from group */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    userID: components["parameters"]["userID"];
                    groupID: components["parameters"]["groupID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/users/{userID}/permissions/{permissionID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                userID: components["parameters"]["userID"];
                permissionID: components["parameters"]["permissionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant permission to user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    userID: components["parameters"]["userID"];
                    permissionID: components["parameters"]["permissionID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        /** Revoke permission from user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    userID: components["parameters"]["userID"];
                    permissionID: components["parameters"]["permissionID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/users/{userID}/authz/resources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                userID: components["parameters"]["userID"];
            };
            cookie?: never;
        };
        /**
         * List resources where the user has effective access
         * @description Returns resources for which the user has any effective access via direct user grants and direct group membership grants.
         *     Effective masks are returned as decimal strings.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    userID: components["parameters"]["userID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "resource_id": "11111111-1111-1111-1111-111111111111",
                         *           "effective_mask": "5"
                         *         }
                         *       ],
                         *       "meta": {
                         *         "total": 1,
                         *         "offset": 0,
                         *         "limit": 20,
                         *         "sort": "resource_id",
                         *         "order": "asc"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["UserAuthzResource"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Domain or user not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/groups/{groupID}/authz/resources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                groupID: components["parameters"]["groupID"];
            };
            cookie?: never;
        };
        /**
         * List resources where the group has direct access
         * @description Returns resources for which the group has any direct grant via group_permissions.
         *     Masks are returned as decimal strings (OR of all direct group grants per resource).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    groupID: components["parameters"]["groupID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "resource_id": "11111111-1111-1111-1111-111111111111",
                         *           "mask": "5"
                         *         }
                         *       ],
                         *       "meta": {
                         *         "total": 1,
                         *         "offset": 0,
                         *         "limit": 20,
                         *         "sort": "resource_id",
                         *         "order": "asc"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["GroupAuthzResource"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Domain or group not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/resources/{resourceID}/authz/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                resourceID: components["parameters"]["resourceID"];
            };
            cookie?: never;
        };
        /**
         * List users with effective access on a resource
         * @description Returns users in the resource's domain whose effective mask on this resource is non-zero.
         *     Effective masks are computed as the OR of direct user grants and grants inherited via group membership.
         *     Effective masks are returned as decimal strings.
         *
         *     Pagination: only `offset` and `limit` are supported. Results are always ordered by `user_id` ascending — `sort` and `order` are not honoured for this endpoint, and any of `search`, `search_type`, `sort`, or `order` in the query string will produce a `400`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    resourceID: components["parameters"]["resourceID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "user_id": "11111111-1111-1111-1111-111111111111",
                         *           "effective_mask": "7"
                         *         }
                         *       ],
                         *       "meta": {
                         *         "total": 1,
                         *         "offset": 0,
                         *         "limit": 20,
                         *         "sort": "user_id",
                         *         "order": "asc"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["ResourceAuthzUser"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Domain or resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/resources/{resourceID}/authz/groups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                resourceID: components["parameters"]["resourceID"];
            };
            cookie?: never;
        };
        /**
         * List groups with direct access on a resource
         * @description Returns groups that have at least one direct grant via `group_permissions` on this resource.
         *     Masks are returned as decimal strings (OR of all direct group grants per group).
         *
         *     Pagination: only `offset` and `limit` are supported. Results are always ordered by `group_id` ascending — `sort` and `order` are not honoured for this endpoint, and any of `search`, `search_type`, `sort`, or `order` in the query string will produce a `400`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of items to skip (pagination). */
                    offset?: components["parameters"]["offsetParam"];
                    /** @description Maximum items to return (clamped to 1–100). */
                    limit?: components["parameters"]["limitParam"];
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    resourceID: components["parameters"]["resourceID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "group_id": "11111111-1111-1111-1111-111111111111",
                         *           "mask": "5"
                         *         }
                         *       ],
                         *       "meta": {
                         *         "total": 1,
                         *         "offset": 0,
                         *         "limit": 20,
                         *         "sort": "group_id",
                         *         "order": "asc"
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: components["schemas"]["ResourceAuthzGroup"][];
                            meta: components["schemas"]["ListMeta"];
                        };
                    };
                };
                /** @description Bad request (invalid pagination params) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Domain or resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/groups/{groupID}/permissions/{permissionID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
                groupID: components["parameters"]["groupID"];
                permissionID: components["parameters"]["permissionID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant permission to group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    groupID: components["parameters"]["groupID"];
                    permissionID: components["parameters"]["permissionID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        /** Revoke permission from group */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                    groupID: components["parameters"]["groupID"];
                    permissionID: components["parameters"]["permissionID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/authz/check": {
        parameters: {
            query: {
                user_id: string;
                resource_id: string;
                access_bit: string;
            };
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
            };
            cookie?: never;
        };
        /** Check if user has access bit on resource */
        get: {
            parameters: {
                query: {
                    user_id: string;
                    resource_id: string;
                    access_bit: string;
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthzCheckResponse"];
                    };
                };
                /** @description Missing required query parameters (`text/plain` from `http.Error`), or invalid `access_bit` (`application/json` from `writeErr` / parse error). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{domainID}/authz/masks": {
        parameters: {
            query: {
                user_id: string;
                resource_id: string;
            };
            header?: never;
            path: {
                domainID: components["parameters"]["domainID"];
            };
            cookie?: never;
        };
        /** List permission masks for user on resource */
        get: {
            parameters: {
                query: {
                    user_id: string;
                    resource_id: string;
                };
                header?: never;
                path: {
                    domainID: components["parameters"]["domainID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthzMasksResponse"];
                    };
                };
                /** @description Missing query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorBody"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ListMeta: {
            /**
             * Format: int64
             * @description Total number of records matching the filter (before pagination).
             */
            total: number;
            offset: number;
            limit: number;
            /** @description The sort field applied (entity-specific). */
            sort: string;
            /**
             * @description The sort direction applied.
             * @enum {string}
             */
            order: "asc" | "desc";
        };
        /**
         * @description User-facing error envelope. The `error` field contains a short, database-agnostic message suitable for display. Internal details (SQL driver text, stack traces) are never included; operators should consult server logs for diagnostics. Messages are stable per error class (404 → "resource not found", 409 → "resource already exists", 500 → "internal server error"). 400 responses may include request-specific validation details (e.g. "cycle detected …").
         * @example {
         *       "error": "resource not found"
         *     }
         */
        ErrorBody: {
            /** @description Human-readable error message; stable per error class, 400s may vary with validation detail. */
            error: string;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        Domain: {
            /** Format: uuid */
            ID: string;
            Title: string;
        };
        TitleBody: {
            title: string;
        };
        PatchTitleBody: {
            title: string;
        };
        /**
         * @description At least one of `title` or `parent_group_id` must be present.
         *     Omit `parent_group_id` to leave the parent unchanged; send `null` to clear (root group).
         */
        GroupPatchBody: {
            title?: string;
            /** Format: uuid */
            parent_group_id?: string | null;
        };
        /** @description At least one of `title` or `bit` must be present. */
        AccessTypePatchBody: {
            title?: string;
            /** @description Decimal or `0x` hex (parsed server-side). */
            bit?: string;
        };
        /** @description At least one of `title`, `resource_id`, or `access_mask` must be present. */
        PermissionPatchBody: {
            title?: string;
            /** Format: uuid */
            resource_id?: string;
            /** @description Decimal or `0x` hex. */
            access_mask?: string;
        };
        User: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            DomainID: string;
            Title: string;
        };
        Group: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            DomainID: string;
            Title: string;
            /** Format: uuid */
            ParentGroupID?: string | null;
        };
        GroupCreateBody: {
            title: string;
            /** Format: uuid */
            parent_group_id?: string | null;
        };
        ParentBody: {
            /** Format: uuid */
            parent_group_id?: string | null;
        };
        Resource: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            DomainID: string;
            Title: string;
        };
        AccessType: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            DomainID: string;
            Title: string;
            /**
             * Format: int64
             * @description Non-negative bit flag as JSON number (`uint64` in Go). Stored as SQLite INTEGER (signed); use range [0, 2^63−1].
             */
            Bit: number;
        };
        AccessTypeCreateBody: {
            title: string;
            /** @description Decimal or `0x` hex (parsed server-side). */
            bit: string;
        };
        Permission: {
            /** Format: uuid */
            ID: string;
            /** Format: uuid */
            DomainID: string;
            Title: string;
            /** Format: uuid */
            ResourceID: string;
            /**
             * Format: int64
             * @description Permission mask as JSON number (`uint64` in Go). Stored as SQLite INTEGER (signed); use range [0, 2^63−1].
             */
            AccessMask: number;
        };
        PermissionCreateBody: {
            title: string;
            /** Format: uuid */
            resource_id: string;
            /** @description Decimal or `0x` hex. */
            access_mask: string;
        };
        AuthzCheckResponse: {
            allowed: boolean;
            /** @description Effective mask as decimal string. */
            effective_mask: string;
        };
        AuthzMasksResponse: {
            /** @description Individual permission masks (uint64); JSON numbers in SQLite-safe non-negative range. */
            masks: number[];
        };
        UserAuthzResource: {
            /** Format: uuid */
            resource_id: string;
            /**
             * @description Effective mask for this user/resource pair as decimal string.
             * @example 5
             */
            effective_mask: string;
        };
        GroupAuthzResource: {
            /** Format: uuid */
            resource_id: string;
            /**
             * @description OR of all direct group grants for this group/resource pair as decimal string.
             * @example 5
             */
            mask: string;
        };
        ResourceAuthzUser: {
            /** Format: uuid */
            user_id: string;
            /**
             * @description Effective mask (OR of direct user grants and group-membership grants) for this user/resource pair as decimal string.
             * @example 7
             */
            effective_mask: string;
        };
        ResourceAuthzGroup: {
            /** Format: uuid */
            group_id: string;
            /**
             * @description OR of all direct group grants for this group/resource pair as decimal string.
             * @example 5
             */
            mask: string;
        };
    };
    responses: never;
    parameters: {
        domainID: string;
        userID: string;
        groupID: string;
        resourceID: string;
        permissionID: string;
        accessTypeID: string;
        /** @description Number of items to skip (pagination). */
        offsetParam: number;
        /** @description Maximum items to return (clamped to 1–100). */
        limitParam: number;
        /** @description Case-insensitive match on title. LIKE wildcards (`%`, `_`) are treated as literals. Match mode controlled by `search_type`. */
        searchParam: string;
        /** @description How to match the search term against title. Only applies when `search` is non-empty. */
        searchTypeParam: "contains" | "starts_with" | "ends_with";
        /** @description Field to sort by (entity-specific; see endpoint description for allowed values). Defaults to `title`. */
        sortParam: string;
        /** @description Sort direction. */
        orderParam: "asc" | "desc";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
